# Generated by Django 2.0.8 on 2018-09-23 12:20

from django.db import migrations, models
import django.db.models.deletion
import editor.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moon')),
                ('percent_illuminated', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=editor.storage.OverwriteStorage(), upload_to='preview')),
                ('selfie_contrast', models.IntegerField(blank=True, default=1, null=True)),
                ('foreground_transparency', models.IntegerField(default=255)),
                ('background_transparency', models.IntegerField(default=255)),
                ('foreground_inverted', models.BooleanField(default=False)),
                ('background_inverted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='final')),
                ('selfie_user', models.CharField(default='@mun_fases', max_length=60)),
                ('background_user', models.CharField(blank=True, max_length=60, null=True)),
                ('background_description', models.CharField(default=':)', max_length=60)),
                ('foreground_user', models.CharField(blank=True, max_length=60, null=True)),
                ('foreground_description', models.CharField(default=':)', max_length=60)),
                ('percent_illuminated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='selfie')),
                ('username', models.CharField(default='', max_length=50)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='texture')),
                ('username', models.CharField(default='none', max_length=50)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='previewimage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background', to='editor.TextureImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='foreground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreground', to='editor.TextureImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='moon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.MoonImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='selfie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.SelfieImage'),
        ),
    ]
