# Generated by Django 2.1.1 on 2018-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='opencv/media')),
                ('percent_illuminated', models.IntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
