# Generated by Django 2.1.1 on 2018-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20180916_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='opencv/media/selfies')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelfieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='opencv/media/selfies')),
                ('username', models.CharField(default='', max_length=50)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
