# Generated by Django 2.1.1 on 2018-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_backgroundimage_selfieimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='editor'),
        ),
        migrations.AlterField(
            model_name='moonimage',
            name='image',
            field=models.ImageField(upload_to='editor'),
        ),
        migrations.AlterField(
            model_name='selfieimage',
            name='image',
            field=models.ImageField(upload_to='editor'),
        ),
    ]
