# Generated by Django 2.1.1 on 2018-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20180916_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
