# Generated by Django 2.1.1 on 2018-09-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_backgroundimage_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundImage',
            new_name='TextureImage',
        ),
    ]
