# Generated by Django 2.1.1 on 2018-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20180919_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textureimage',
            name='username',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
