# Generated by Django 2.1.1 on 2018-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20180920_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewimage',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='previewimage',
            name='background_description',
            field=models.CharField(default=':)', max_length=60),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='background_user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='foreground_description',
            field=models.CharField(default=':)', max_length=60),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='foreground_user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='percent_illuminated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previewimage',
            name='selfie_user',
            field=models.CharField(default='@mun_fases', max_length=60),
        ),
    ]
