# Generated by Django 2.1.1 on 2018-09-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20180920_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewimage',
            name='background_description',
        ),
        migrations.RemoveField(
            model_name='previewimage',
            name='background_user',
        ),
        migrations.RemoveField(
            model_name='previewimage',
            name='foreground_description',
        ),
        migrations.RemoveField(
            model_name='previewimage',
            name='foreground_user',
        ),
        migrations.RemoveField(
            model_name='previewimage',
            name='percent_illuminated',
        ),
        migrations.RemoveField(
            model_name='previewimage',
            name='selfie_user',
        ),
        migrations.AddField(
            model_name='previewimage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background', to='editor.TextureImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='foreground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreground', to='editor.TextureImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='moon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.MoonImage'),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='selfie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.SelfieImage'),
        ),
    ]
