# Generated by Django 2.1.1 on 2018-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20180920_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='preview'),
        ),
    ]
